const GameActionTypes = {
  GENERATE_BOARD: 'GENERATE_BOARD',

  SET_BOARD_NUMBERS: 'SET_BOARD_NUMBERS',
  SET_BOARD_OPENSTATES: 'SET_BOARD_OPENSTATES',

  SET_CARD_STATE: 'SET_CARD_STATE',
  SET_PAIR_STATE: 'SET_PAIR_STATE',

  SET_BOARD_STEPS: 'SET_BOARD_STEPS',

  SET_GAME_STATE: 'SET_GAME_STATE',
};

export default GameActionTypes;
